# Form implementation generated from reading ui file 'componentsUtilitiesView.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_componentsUtilitiesView(object):
    def setupUi(self, componentsUtilitiesView):
        componentsUtilitiesView.setObjectName("componentsUtilitiesView")
        componentsUtilitiesView.resize(1124, 568)
        self.centralwidget = QtWidgets.QWidget(parent=componentsUtilitiesView)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(180, 50, 751, 421))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.hLayoutVCU = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.hLayoutVCU.setContentsMargins(0, 0, 0, 0)
        self.hLayoutVCU.setObjectName("hLayoutVCU")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(940, 44, 171, 421))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Extr")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.AttValueC = QtWidgets.QLabel(parent=self.groupBox)
        self.AttValueC.setGeometry(QtCore.QRect(20, 70, 131, 21))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Extr")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.AttValueC.setFont(font)
        self.AttValueC.setObjectName("AttValueC")
        self.AttUtilityC = QtWidgets.QLabel(parent=self.groupBox)
        self.AttUtilityC.setGeometry(QtCore.QRect(20, 210, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Extr")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.AttUtilityC.setFont(font)
        self.AttUtilityC.setObjectName("AttUtilityC")
        self.plainTextAVC = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.plainTextAVC.setGeometry(QtCore.QRect(20, 100, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Extr")
        font.setPointSize(17)
        self.plainTextAVC.setFont(font)
        self.plainTextAVC.setObjectName("plainTextAVC")
        self.plainTextAU = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.plainTextAU.setGeometry(QtCore.QRect(20, 250, 131, 56))
        font = QtGui.QFont()
        font.setFamily("Neue Haas Grotesk Text Pro Extr")
        font.setPointSize(11)
        self.plainTextAU.setFont(font)
        self.plainTextAU.setObjectName("plainTextAU")
        componentsUtilitiesView.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=componentsUtilitiesView)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 26))
        self.menubar.setObjectName("menubar")
        componentsUtilitiesView.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=componentsUtilitiesView)
        self.statusbar.setObjectName("statusbar")
        componentsUtilitiesView.setStatusBar(self.statusbar)

        self.retranslateUi(componentsUtilitiesView)
        QtCore.QMetaObject.connectSlotsByName(componentsUtilitiesView)

    def retranslateUi(self, componentsUtilitiesView):
        _translate = QtCore.QCoreApplication.translate
        componentsUtilitiesView.setWindowTitle(_translate("componentsUtilitiesView", "MainWindow"))
        self.groupBox.setTitle(_translate("componentsUtilitiesView", "Attribute"))
        self.AttValueC.setText(_translate("componentsUtilitiesView", "Attribute Value"))
        self.AttUtilityC.setText(_translate("componentsUtilitiesView", "Utility"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    componentsUtilitiesView = QtWidgets.QMainWindow()
    ui = Ui_componentsUtilitiesView()
    ui.setupUi(componentsUtilitiesView)
    componentsUtilitiesView.show()
    sys.exit(app.exec())
