# Form implementation generated from reading ui file 'modifyAltCon.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ModifyAltCon(object):
    def setupUi(self, ModifyAltCon):
        ModifyAltCon.setObjectName("ModifyAltCon")
        ModifyAltCon.resize(722, 679)
        self.centralwidget = QtWidgets.QWidget(parent=ModifyAltCon)
        self.centralwidget.setObjectName("centralwidget")
        ModifyAltCon.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=ModifyAltCon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 722, 26))
        self.menubar.setObjectName("menubar")
        ModifyAltCon.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=ModifyAltCon)
        self.statusbar.setObjectName("statusbar")
        ModifyAltCon.setStatusBar(self.statusbar)

        self.retranslateUi(ModifyAltCon)
        QtCore.QMetaObject.connectSlotsByName(ModifyAltCon)

    def retranslateUi(self, ModifyAltCon):
        _translate = QtCore.QCoreApplication.translate
        ModifyAltCon.setWindowTitle(_translate("ModifyAltCon", " Modifying alternative consequences for an attribute"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ModifyAltCon = QtWidgets.QMainWindow()
    ui = Ui_ModifyAltCon()
    ui.setupUi(ModifyAltCon)
    ModifyAltCon.show()
    sys.exit(app.exec())
